SubjectI=vertcat({Master_results.Subject});
WordlistI=vertcat({Master_results.WordList});
ChannelI=cell2mat(vertcat({Master_results.Channel}))';
% DepthI=cell2mat(vertcat({Master_results.NormDepth}))';
Ind=1:length(SubjectI);
Cond={'Cue','Onset'};
freq={'delta','theta','alpha','beta1','beta2','Gamma','Hgamma'};
Final=[];
h=1; %overall count of condition/frequency combos
for c=1:length(Cond)
    for f=1:length(freq)
        x1=vertcat({Master_results.([freq{f} '_' Cond{c} '_zAmp_pvalue'])});
        act_ind1=find(logical(~cell2mat(cellfun(@(x) sum(x==1),x1,'Uni',0)))');
        t1=vertcat({Master_results.([freq{f} '_' Cond{c} '_zAMP_time'])});
        z=vertcat({Master_results.([freq{f} '_' Cond{c} '_zAMP'])});
        z=z(act_ind1);
        t1=t1(act_ind1);
        t1=horzcat(t1{:})';
        nz=length(z);
        act_ind1=cellfun(@(x,y) repmat(x,numel(y),1),num2cell(act_ind1)',z,'Uni',0);
        act_ind1=vertcat(act_ind1{:});
        z=cell2mat(horzcat(z{:})');
        zp=z>0;
        x2=vertcat({Master_results.([freq{f} '_' Cond{c} '_pvalue'])});
        act_ind2=find(logical(~cell2mat(cellfun(@(x) sum(x==1),x2,'Uni',0)))');
        t2=vertcat({Master_results.([freq{f} '_' Cond{c} '_IPC_time'])});
        IPC=vertcat({Master_results.([freq{f} '_' Cond{c} '_IPC'])});
        IPC=IPC(act_ind2);
        ni=length(IPC);
        t2=t2(act_ind2);
        t2=horzcat(t2{:})';
        act_ind2=cellfun(@(x,y) repmat(x,numel(y),1),num2cell(act_ind2)',IPC,'Uni',0);
        act_ind2=vertcat(act_ind2{:});
        IPC=cell2mat(horzcat(IPC{:})');
        [overlap,o1,o2]=intersect(act_ind1,act_ind2);
        for o=1:length(overlap)
            to1=cell2mat(cellfun(@(x) x(1):1/1200:x(2),  t1(o1(o)),'Uni',0));
            to2=cell2mat(cellfun(@(x) x(1):1/1200:x(2),  t2(o2(o)),'Uni',0));
            overlap(o)=(sum(intersect(to1,to2)))>0;
        end
        Final(h).Frequency=freq{f};
        Final(h).TimeLock=Cond{c};
        Final(h).NumSubjectsPower =length(unique(SubjectI(act_ind1)));
        Final(h).NumSessionsPower= length(unique(cellfun(@(x,y) [x '_' y],SubjectI(act_ind1),WordlistI(act_ind1),'Uni',0)));
        Final(h).mean_powerp=mean(z(zp));
        Final(h).std_powerp=std(z(zp));
        Final(h).positive=sum(zp);
        Final(h).mean_powern=mean(z(~zp));
        Final(h).std_powern=std(z(~zp));
        Final(h).negative=sum(~zp);
        g=cellfun(@min,t1,'Uni',0);
        g=vertcat(g{:});
        Final(h).mean_time_ap=mean(g(zp));
        Final(h).std_time_ap=std(g(zp));
        Final(h).mean_time_an=mean(g(~zp));
        Final(h).std_time_an=std(g(~zp));
        % [r,p]=corr(DepthI(act_ind1),z,'rows','complete');
        % Final(h).power_rho=r;
        % Final(h).power_p=p;
        Final(h).NumSessionsIPC=length(unique(cellfun(@(x,y) [x '_' y],SubjectI(act_ind2),WordlistI(act_ind2),'Uni',0)));
        Final(h).NumSubjectsIPC=length(unique(SubjectI(act_ind2)));
        Final(h).mean_IPC=mean(IPC);
        Final(h).std_IPC=std(IPC);
        g=cellfun(@min,t2,'Uni',0);
        g=vertcat(g{:});
        Final(h).mean_time_p=mean(g);
        Final(h).std_time_p=std(g);
        % [r,p]=corr(DepthI(act_ind2),IPC,'rows','complete');
        % Final(h).IPC_rho=r;
        % Final(h).IPC_p=p;
        Final(h).overlap=sum(overlap);
        h=h+1;
    end
end